language: haskell
before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq libmagickwand-dev libmagickcore-dev imagemagick
  - travis/cabal-apt-install --only-dependencies --force-reinstalls
